---
os_version: "8"
sign_node_dnf_packages:
  - "python3"
  - "gcc"
  - "gcc-c++"
  - "python3-devel"
  - "python3-virtualenv"
  - "cmake"
  - "python3-pycurl"
  - "libcurl-devel"
  - "openssl-devel"
  - "git"
  - "sudo"
  - "nginx"
  - "rpm-sign"
  - "tree"
  - "mlocate"
  - "keyrings-filesystem"
  - "pinentry"
  - "ubu-keyring"
  - "debian-keyring"
  - "raspbian-keyring"
...
