---

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Download CAS binary from Github
  become: yes
  get_url:
    url: https://github.com/codenotary/cas/releases/download/v{{ cas_version }}/cas-v{{ cas_version }}-linux-{{ cas_architecture }}
    dest: /usr/local/bin/cas
    mode: 0755
    owner: "root"
    group: "root"
...
