---

- name: Create service user
  user:
    name: "{{ service_user }}"
    groups: wheel, mock
    append: yes
    state: present
    create_home: yes
    generate_ssh_key: yes

- name: Create subsequent directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
  with_items: "{{ working_directories }}"

- name: Generate build node config
  template:
    src: build_node.j2
    dest: "{{ final_conf_dir }}/build_node.yml"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: "0644"

- name: Cloud build node repository
  git:
    repo: https://github.com/AlmaLinux/albs-node.git
    dest: "{{ build_node_working_directory }}/albs-node"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes

- name: Create venv
  become: yes
  become_user: "{{ service_user }}"
  pip:
    virtualenv: "{{ build_node_venv_directory }}"
    virtualenv_command: "python3 -m venv"
    requirements: "{{ build_node_requirements_path }}"
    virtualenv_site_packages: yes
