---

- name: Generate a service's config
  template:
    dest: "{{ item.dest }}/{{ item.dname }}"
    src: "{{ item.sname }}"
    mode: "{{ item.mode }}"
    force: yes
  with_items: "{{ generated_configs }}"
