---

- name: Check if it's a clean installation
  stat:
    path: "{{ volumes_root }}/is_clean_installation"
  register: is_clean_installation

- name: Change pulp password
  community.docker.docker_container_exec:
    container: "{{ container_name_prefix }}_pulp_1"
    command: "bash -c 'pulpcore-manager reset-admin-password -p {{ pulp_password }}'"
  register: result
  until: result is succeeded
  retries: 10
  delay: 30
  when: is_clean_installation.stat.exists == False

- name: Enable pulp database external access
  community.docker.docker_container_exec:
    container: "{{ container_name_prefix }}_pulp_1"
    command: >-
      bash -c "
      if ! grep -q 'listen_addresses = \*' /var/lib/pgsql/data/postgresql.conf; then
        echo \"listen_addresses = '*'\" >> /var/lib/pgsql/data/postgresql.conf;
      fi &&
      if ! grep -q 'host all all 0.0.0.0/0 md5' /var/lib/pgsql/data/pg_hba.conf; then
        echo \"host all all 0.0.0.0/0 md5\" >> /var/lib/pgsql/data/pg_hba.conf;
      fi &&
      if ! grep -q 'host all all ::/0 md5' /var/lib/pgsql/data/pg_hba.conf; then
        echo \"host all all ::/0 md5\" >> /var/lib/pgsql/data/pg_hba.conf;
      fi &&
      runuser postgres -c 'echo \"ALTER USER postgres WITH PASSWORD '\''{{ pulp_password }}'\'';\" | /usr/bin/psql'"
  when: is_clean_installation.stat.exists == False

- name: Stop pulp container
  community.docker.docker_container:
    name: "{{ container_name_prefix }}_pulp_1"
    state: stopped
  when: is_clean_installation.stat.exists == False

- name: Start pulp container
  community.docker.docker_container:
    name: "{{ container_name_prefix }}_pulp_1"
    state: started
  when: is_clean_installation.stat.exists == False

- name: Bootstrap permissions
  community.docker.docker_container_exec:
    container: "{{ container_name_prefix }}_web_server_1"
    command: bash -c 'python3 scripts/bootstrap_permissions.py || true'
  when: is_clean_installation.stat.exists == False

- name: Bootstrap repositories
  community.docker.docker_container_exec:
    container: "{{ container_name_prefix }}_web_server_1"
    command: python3 scripts/bootstrap_repositories.py -c reference_data/platforms.yaml
  register: result
  until: result is succeeded
  retries: 10
  delay: 15
  when: is_clean_installation.stat.exists == False

- name: Activate user
  community.docker.docker_container_exec:
    container: "{{ container_name_prefix }}_web_server_1"
    command: bash -c 'python3 scripts/manage_users.py -e base_user@almalinux.org -t AlmaLinux_team --verify --superuser || true'
  when: is_clean_installation.stat.exists == False

- name: Checking if GPG key exists on web_server
  tags: add_pgp_to_web_server
  ansible.builtin.uri:
    url: "{{ albs_api_url_ext }}sign-keys/"
    method: GET
    headers:
      accept: application/json
      Authorization: "Bearer {{ albs_jwt }}"
    return_content: true
  register: gpg_request_output

- name: Adding GPG key to the web_server
  tags: add_pgp_to_web_server
  ansible.builtin.uri:
    url: "{{ albs_api_url_ext }}sign-keys/new/"
    method: POST
    headers:
      accept: application/json
      Authorization: "Bearer {{ albs_jwt }}"
      Content-Type: application/json
    body:
      name: Test GPG key
      description: test
      keyid: "{{ gpg_key_fingerprint.stdout[-16:] }}"
      fingerprint: "{{ gpg_key_fingerprint.stdout | trim }}"
      public_url: http://test.com
      platform_id: 1
    body_format: json
    status_code:
      - 200
      - 201
  when: gpg_request_output.json|length == 0

- name: Bootstrap flavours
  community.docker.docker_container_exec:
    container: "{{ container_name_prefix }}_web_server_1"
    command: python3 scripts/manage_flavours.py -c reference_data/platform_flavors.yaml
  when: is_clean_installation.stat.exists == False

- name: ensure file exists
  copy:
    content: ""
    dest: "{{ volumes_root }}/is_clean_installation"
    force: false
