---

- name: Verify docker compose plugin (v2) is available
  shell: "docker compose version"
  changed_when: False

- name: Set docker_compose variable
  set_fact:
    docker_compose: "docker compose"

- name: Create and start services
  block:
    - name: Get list of services
      shell: "{{ docker_compose }} -p {{ container_name_prefix }} config --services"
      args:
        chdir: "{{ sources_root }}/albs-web-server"
      register: services

    - name: Create and start each service individually
      shell: "{{ docker_compose }} -p {{ container_name_prefix }} --compatibility up -d --build --force-recreate {{ item }}"
      args:
        chdir: "{{ sources_root }}/albs-web-server"
      when:
        - item not in excluded_containers
        - item not in (pre_bootstrap_excluded_containers | default([]))
      loop: "{{ services.stdout_lines }}"
  when:
    - docker_compose != "not found"
    - (excluded_containers | length > 0) or (pre_bootstrap_excluded_containers | default([]) | length > 0)

- name: Create and start services
  shell: "{{ docker_compose }} -p {{ container_name_prefix }} --compatibility up -d --build --force-recreate"
  args:
    chdir: "{{ sources_root }}/albs-web-server"
  register: output
  when:
    - docker_compose != "not found"
    - excluded_containers | length == 0
    - pre_bootstrap_excluded_containers | default([]) | length == 0

- debug:
    var: output

- name: Fail if docker-compose not found
  fail:
    msg: "docker-compose not found"
  when: docker_compose == "not found"
