---

- name: Configure Nginx to redirect pulp to the ALBS address
  ansible.builtin.template:
    src: pulp.conf.j2
    dest: /etc/nginx/conf.d/pulp.conf
    mode: "0644"
  register: nginx_conf
  become: "yes"

- name: Start and enable Nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: "yes"

- name: Add pulp to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 pulp"
    state: present
  become: "yes"

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded
  when: nginx_conf.changed
  become: "yes"

...
