---
- name: Deploy the ALBS
  hosts: all
  connection: "{{ 'local' if use_local_connection else 'ssh' }}"
  roles:
    - role: geerlingguy.docker
      become: true
      vars:
        docker_install_compose_plugin: true
        docker_users:
          - "{{ ansible_user_id }}"
    - dev_deploy
...
